# Generated by Django 3.2.3 on 2021-11-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='users/products/product-1.jpg', null=True, upload_to='users/products-images', verbose_name='Image'),
        ),
    ]
