# Generated by Django 3.2.6 on 2021-11-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20211118_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default='products-images/default-image.jpg', null=True, upload_to='users/products-images', verbose_name='Images'),
        ),
    ]
